{% set version = "25.02.0" %}

package:
  name: scipp
  version: "{{ version }}"

source:
  url: https://github.com/scipp/scipp/archive/{{ version }}.tar.gz
  sha256: 11430eb1e27fb41018897f1425e01071a5d0f91565e992b3c3c8b21782371a68

build:
  skip: true  # [py<310]
  script_env:
    - GIT_VERSION_INFO={{ version }}
  number: 2
  missing_dso_whitelist:
    - '*'        # [win]
  script:
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE="%PYTHON%" -DCONDA_FORGE_BUILD=ON  # [win]
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=$PYTHON -DCONDA_FORGE_BUILD=ON  # [unix]
    - cmake --build --preset build
    - ctest --preset test  # [build_platform == target_platform]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cmake
    - conan ==1.66
    - ninja
    - make  # [unix]
  host:
    - python
    - tbb-devel
    - libboost-headers
    - eigen
    - pybind11
    - benchmark
    - gmock ==1.15.2
    - gtest ==1.15.2
  run:
    - numpy
    - python
    - tbb

test:
  imports:
    - scipp
  requires:
    - numba
    - bs4
    - h5py
    - hypothesis
    - pandas
    - pytest
    - python-graphviz
    - xarray
    - ipython
    - scipy >=1.7.0
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests


about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LLNL_UNITS_LICENSE
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/

extra:
  recipe-maintainers:
    - MridulS
